online-mode=false
enforce-secure-profile=false
view-distance=6
simulation-distance=5
max-players=10
network-compression-threshold=128
enable-command-block=true
pvp=true
max-tick-time=60000
level-seed=1555494347652201185
enable-rcon=true
rcon.port=25575
rcon.ip=127.0.0.1
rcon.password=${{secrets.RCON_PASSWORD}}