server-name=loot-low-bedrock
gamemode=survival
force-gamemode=false
difficulty=normal
allow-cheats=false
max-players=10
online-mode=true
allow-list=false
server-port=19132
server-ip=0.0.0.0
server-portv6=19133
enable-lan-visibility=false
view-distance=8
tick-distance=4
player-idle-timeout=30
max-threads=0
level-name=world
level-seed=1555494347652201185
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=false
compression-threshold=256
compression-algorithm=zlib
allow-outdated-client=true
emit-server-telemetry=false
rcon.port=25575
rcon.password=Achin0007
enable-rcon=true