online-mode=false
view-distance=6
simulation-distance=4
max-players=10
network-compression-threshold=128
enable-command-block=true
level-seed=1555494347652201185
transport=raknet
enable-rcon=true
rcon.port=25575
rcon.ip=127.0.0.1
rcon.password=CHANGE_ME